version: 2

updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "feat:"
    target-branch: "main"
    open-pull-requests-limit: 5
    reviewers:
      - "shuidi-l"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore:"
    target-branch: "main"
    open-pull-requests-limit: 3
    reviewers:
      - "shuidi-l"

  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "feat:"
    target-branch: "main"
    open-pull-requests-limit: 5
    reviewers:
      - "shuidi-l"
